stages:
  - scan
  - build_and_deploy

scan_dockerfiles:
  stage: scan
  image: 
    name: checkmarx/kics:latest
    entrypoint: [""]
  script:
    - kics scan --path Dockerfile --output-path kics-results.json
    - |
      if grep -q '"severity": "HIGH"' kics-results.json; then
        echo "High severity issue found, failing the job."
        exit 1
      fi
  only:
    - branches

build_and_deploy:
  stage: build_and_deploy
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  only:
    - branches
  except:
    - master
  dependencies:
    - scan_dockerfiles