version: '3'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 5000:5000
    volumes:
      - ./frontend:/app
    networks:
      - default

  chat-service:
    container_name: chat-service
    build: 
      context: ./backend/chat-service
      dockerfile: Dockerfile.app
    ports:
      - 5001:5001
    networks:
      - chat-service-network
      - default

  chat-service-db:
    container_name: chat-service-db
    build: 
      context: ./backend/chat-service
      dockerfile: Dockerfile.db
    volumes:
      - chat-service-db-data:/var/lib/postgresql/data
    networks:
      - chat-service-network

  user-service:
    container_name: user-service
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile.app
    ports:
      - 5002:5002
    networks:
      - user-service-network
      - default

  user-service-db:
    container_name: user-service-db
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile.db
    volumes:
      - user-service-db-data:/var/lib/postgresql/data
    networks:
      - user-service-network

volumes:
  user-service-db-data:
  chat-service-db-data:

networks:
  chat-service-network:
    driver: bridge
  user-service-network:
    driver: bridge
  default:
    driver: bridge