# use an official postgres runtime
FROM postgres:14-alpine

# copy the init-db.sql file to the docker-entrypoint-initdb.d directory
COPY init-db.sql /docker-entrypoint-initdb.d/

# define the environment variables
ENV POSTGRES_DB=postgres-db
ENV POSTGRES_USER=normaluser
ENV POSTGRES_PASSWORD=user
